---

- name: Ensure directory exists
  file:
    path: "{{ gitpath }}"
    state: directory
    mode: '0750'

- name: Clone NYScripts repo
  git:
    repo: git@github.com:nickyeoman/NYScripts.git
    dest: "{{ gitpath }}/NYScripts"
    key_file: "{{ gitkey }}"
    accept_hostkey: yes
    version: master
    update: no

- name: Clone Docker compose cookbooks repo
  git:
    repo: git@github.com:nickyeoman/docker-compose-cookbooks.git
    dest: "{{ gitpath }}/docker-cookbooks"
    key_file: "{{ gitkey }}"
    accept_hostkey: yes
    version: master
    update: no

- name: Clone ansible public repo
  git:
    repo: git@github.com:nickyeoman/docker-compose-cookbooks.git
    dest: "{{ gitpath }}/docker-cookbooks"
    key_file: "{{ gitkey }}"
    accept_hostkey: yes
    version: master
    update: no
