---

- name: set environment
  copy:
    src: environment
    dest: /etc/environment
    mode: 0644
    owner: root
    group: root
    force: yes

- name: bash aliases for root
  copy:
    src: bash_aliases
    dest: /root/.bash_aliases
    mode: 0644
    owner: root
    group: root

- name: bash aliases for user
  copy:
    src: bash_aliases
    dest: /home/{{ your_username }}/.bash_aliases
    mode: 0764
    owner: "{{ your_username }}"
    group: "{{ your_username }}"
