---

- name: etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.name }}
    marker: '# {mark} ANSIBLE MANGED BLOCK {{ item.name }}'
  loop:
    # Hosts
    - {name: vbox.nickyeoman.com, ip: 192.168.69.200 }
    - {name: tor.nickyeoman.com, ip: 192.168.69.204 }
    - {name: kendra.nickyeoman.com, ip: 192.168.69.202 }
    - {name: stage.nickyeoman.com, ip: 192.168.69.203 }
    - {name: nas.nickyeoman.com, ip: 192.168.69.210 }
    - {name: nixbuntu.nickyeoman.com, ip: 192.168.69.215 }
    - {name: danica.nickyeoman.com, ip: 192.168.69.216 }
    - {name: cx2.nickyeoman.com, ip: 192.168.69.249 }
