wtf:
  colors:
    border:
      focusable: limegreen
      focused: yellow
      normal: darkgreen
  grid:
    #187x55
    columns: [1,20,20,20,20,20,20,20,20,20,7,90]
    rows: [1,3,5,5,5,5,5,5,5,5,5,5,5,90]
  refreshInterval: 1
  mods:

    docker:
      type: docker
      title: Containers
      enabled: true
      labelColor: lightblue
      position:
        top: 2
        left: 1
        height: 7
        width: 2
      refreshInterval: 200

    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 4
        left: 7
        height: 2
        width: 3
      refreshInterval: 300

    uptime:
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 9
      refreshInterval: 60
      type: cmdrunner

    bandwidth:
      type: "cmdrunner"
      cmd: "vnstat"
      enabled: true
      position:
        top: 4
        left: 3
        height: 5
        width: 4
      refreshInterval: 300
      title: "Bandwidth"

    disks:
      type: "cmdrunner"
      cmd: "wtf-ds"
      enabled: true
      position:
        top: 2
        left: 3
        height: 2
        width: 4
      refreshInterval: 60
      title: "Disks"

    digitalclock:
      color: darkgreen
      enabled: true
      font: bigfont
      hourFormat: 12
      position:
        top: 2
        left: 7
        height: 2
        width: 3
      refreshInterval: 1
      title: "big clock"
      type: "digitalclock"

    prettyweather:
      enabled: true
      city: "Summerland"
      title:: "Summerland BC"
      position:
        top: 6
        left: 7
        height: 2
        width: 3
      refreshInterval: 300
      unit: "m"
      view: 0
      language: "en"
