# main playbook
# TODO: show how to actually run this from cron

- hosts: all
  pre_tasks:
    - name: apt update
      apt:
        update_cache: yes

  roles:
    - apt
    - bin
    - cronjobs
    - docker_install
    - etchosts
    - git_repos
    - git_user
    - docker
    - hugo
    - timezone

- hosts: xfce
  roles:
    - atom
    - simplescreenrecorder
    - xfce
    - nextcloud-client
