# main playbook
# TODO: show how to actually run this from cron

- hosts: all
  pre_tasks:
    - name: apt update
      apt:
        update_cache: yes

  roles:
    - timezone
    - docker_install
    - apt
    - git_user
    - bin
    - cronjobs
    - git_repos

- hosts: xfce
  roles:
    - xfce
    - atom
    - simplescreenrecorder
